check DNS before trying to download an ISO

diff --git a/usr/sbin/omv-grubiso b/usr/sbin/omv-grubiso
--- a/usr/sbin/omv-grubiso
+++ b/usr/sbin/omv-grubiso
@@ -37,8 +37,23 @@ GPARTEDLIVE_ISO="gparted-live-${GPARTEDLIVE_VERSION}-i686.iso"
 GRUB="/etc/default/grub"
 GRUB_CFG="/boot/grub/grub.cfg"
 
+checkDNS()
+{
+  host="/usr/bin/host"
+  if [ -f "${host}" ]; then
+    if ! ${host} sourceforge.net > /dev/null; then
+      echo "DNS error.  Exiting ..."
+      exit 0
+    else
+      echo "DNS OK."
+    fi
+  fi
+}
+
 installclonezilla()
 {
+    checkDNS
+
     echo "Installing Clonezilla..."
     if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
         rm -f ${ISO_PATH}/clonezilla*.iso
@@ -64,6 +79,8 @@ EOF
 
 installsysresccd()
 {
+    checkDNS
+
     if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
         rm -f ${ISO_PATH}/systemrescuecd*.iso
         wget "https://osdn.net/projects/systemrescuecd/storage/releases/${SYSRESCCD_VERSION}/${SYSRESCCD_ISO}" -O ${ISO_PATH}/${SYSRESCCD_ISO} 2>&1
@@ -89,6 +106,8 @@ EOF
 
 installgpartedlive()
 {
+    checkDNS
+
     if [ ! -f "${ISO_PATH}/${GPARTEDLIVE_ISO}" ]; then
         rm -f ${ISO_PATH}/gparted-live*.iso
         wget "https://downloads.sourceforge.net/gparted/${GPARTEDLIVE_ISO}" -O ${ISO_PATH}/${GPARTEDLIVE_ISO} 2>&1
